<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page import="java.util.*, java.text.DecimalFormat" %>
<%@ include file="header.jsp" %>

<%            String acc = (String) request.getAttribute("accountNumber");
    String name = (String) request.getAttribute("customerName");
    Double total = (Double) request.getAttribute("totalAmount");
    Date date = (Date) request.getAttribute("billDate");
    List<Map<String, Object>> items = (List<Map<String, Object>>) request.getAttribute("bookDetails");
    Integer billId = (Integer) request.getAttribute("billId");
    DecimalFormat df = new DecimalFormat("#,##0.00");
%>

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Bill Preview</title>
        <link rel="stylesheet" href="css/Style.css" />
        <style>
            body {
                font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
                background-color: #F5ECD9;
                margin: 0;
                padding: 20px;
            }
            .container {
                background-color: white;
                padding: 25px;
                border-radius: 10px;
                max-width: 800px;
                margin: auto;
                box-shadow: 0 0 15px rgba(0,0,0,0.1);
                overflow-x: auto;
            }
            .title {
                text-align: center;
                background-color: #4B2E1E; 
                color: #F5ECD9; 
                padding: 15px;
                border-radius: 8px;
                margin-bottom: 20px;
                font-weight: bold;
                box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);
            }
            table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 15px;
                background-color: #fff;
                box-shadow: 0 0 10px rgba(0,0,0,0.05);
            }
            table, th, td {
                border: 1px solid #C2B280; 
            }
            th {
                background-color: #4B2E1E; 
                color: #F5ECD9;
                padding: 12px 15px;
                text-align: center;
            }
            td {
                padding: 10px 15px;
                color: #4B2E1E; 
                text-align: center;
            }
            tfoot td {
                font-weight: bold;
                text-align: right;
                background-color: #F5ECD9; 
                color: #4B2E1E;
            }
            .text-center {
                text-align: center;
            }
            .btn-print {
                background-color: #708238; 
                color: white;
                padding: 10px 25px;
                border: none;
                border-radius: 5px;
                font-size: 16px;
                cursor: pointer;
                margin-top: 20px;
                display: block;
                margin-left: auto;
                margin-right: auto;
                box-shadow: 0 2px 5px rgba(0,0,0,0.15);
                transition: background-color 0.3s ease;
            }
            .btn-print:hover {
                background-color: #566b2f;
            }
            @media print {
                .app-header {
                    display: none !important;
                }
                .btn-print, .submit-btn, .logout-link, .help-link {
                    display: none !important;
                }
                body {
                    margin: 0;
                    background: white;
                }
            }
        </style>

    </head>
    <body>
        <div class="container">
            <h3 class="title">Bill Preview</h3>

            <div>
                <p><strong>Invoice Number :</strong> <%= (billId != null) ? billId : "N/A"%></p>
                <p><strong>Customer Name:</strong> <%= (name != null) ? name : "Unknown Customer"%></p>
                <p><strong>Account Number:</strong> <%= (acc != null) ? acc : "N/A"%></p>
                <p><strong>Date:</strong> <%= (date != null) ? new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(date) : "N/A"%></p>
            </div>

            <div class="mt-3">
                <p><strong>Generated By:</strong> <%= (username != null) ? username : "Unknown User"%></p>
            </div>

            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Book Title</th>
                        <th>Quantity</th>
                        <th>Unit Price (LKR)</th>
                        <th>Total (LKR)</th>
                    </tr>
                </thead>
                <tbody>
                    <%
                        int i = 1;
                        if (items != null) {
                            for (Map<String, Object> item : items) {
                    %>
                    <tr>
                        <td><%= i++%></td>
                        <td><%= item.get("title")%></td>
                        <td style="text-align:center"><%= item.get("qty")%></td>
                        <td style="text-align:right"><%= df.format(item.get("unitPrice"))%></td>
                        <td style="text-align:right"><%= df.format(item.get("total"))%></td>
                    </tr>
                    <%
                        }
                    } else {
                    %>
                    <tr><td colspan="5" class="text-center">No items found</td></tr>
                    <%
                        }
                    %>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="4" class="text-right">Grand Total</td>
                        <td><%= (total != null) ? df.format(total) : "0.00"%></td>
                    </tr>
                </tfoot>
            </table>

            <button class="btn-print" onclick="window.print()">Print Bill</button>

        </div>

        <div>
            <%@ include file="footer.jsp" %>
        </div>

    </body>
</html>
